### PR TITLE
Fix whitespace and remove print

### LINKED ISSUE #11: Crash when the path contains a space
I tried to cd to a directory where the path contains a space (e.g., `/Users/henry/test dir`). It crashes because zoxide can not find the path. The log shows that the content after the space in the path are strip off.

image

### PR DESCRIPTION
**Pull request by naefl**
Fixes #11

Additionally removes the print statement which I found highly distracting. I think it's okay to notify about an error, but printing about suceeding in it's intended action doesn't seem necessary. Feel free to cherry pick only the fix if you disagree

### CODE REVIEW

File: lua/telescope/_extensions/zoxide/config.lua [hunk 1]
```diff
@@ -14,9 +14,6 @@ local default_config = {
       action = function(selection)
         vim.cmd("cd " .. selection.path)
       end,
-      after_action = function(selection)
-        print("Directory changed to " .. selection.path)
```
Comment (jvgrootveld) [inline lua/telescope/_extensions/zoxide/config.lua:18]: The main reason I added this, is to have a clear default with optionally overriding it (see [overridable-config](https://github.com/jvgrootveld/telescope-zoxide#overridable-config) I could understand some find it annoying, but I don't know what the majority wants as a default.

Anyone could just override it with an empty function. What do you think?
1. Have a print by default where people can optionally override it with an empty function (maybe add it as a suggestion in de Readme)
2. Have an empty function by default where people can optionally override it with a print function (example already in the Readme)

PS. On a side note, although small, this changes the default behaviour of the current user-base.

File: lua/telescope/_extensions/zoxide/list.lua [hunk 2]
```diff
@@ -60,20 +60,14 @@ local fuzzy_with_z_score_bias = function(opts)
...
-  local score = 0
-  local item_path = item
-
-  if #items > 1 then
-    score = tonumber(items[1])
-    item_path = items[2]
-  end
+  local trimmed = string.gsub(item, '^%s*(.-)%s*$', '%1')
+  local item_path = string.gsub(trimmed, '^[^%s]* (.*)$', '%1')
+  local score = string.gsub(trimmed, '^([^%s]*) .*$', '%1')
```
Comment (jvgrootveld) [inline lua/telescope/_extensions/zoxide/list.lua:65]: N00b question. The idea as that the `score` was facilitated as a `number` type, so anyone can interpret it as a number (sort, math, go crazy).

I am a bit out of Lua at the moment, could this cause any problems for the existing user-base?

File: lua/telescope/_extensions/zoxide/list.lua [hunk 3]
```diff
@@ -60,20 +60,14 @@ local fuzzy_with_z_score_bias = function(opts)
 end
 
 local entry_maker = function(item)
-  local items = vim.split(string.gsub(item, '^%s*(.-)%s*$', '%1'), " ")
-  local score = 0
-  local item_path = item
-
-  if #items > 1 then
```
Comment (jvgrootveld) [inline lua/telescope/_extensions/zoxide/list.lua:67]: I can't remember why I added this check when I created this plugin. Is this still handled on your new implementation?

**Comment by jvgrootveld** [comment]
@naefl Thanks a lot for helping! I haven't created much time to work on this repository.

File: lua/telescope/_extensions/zoxide/config.lua (hunk 1 above)
Comment (naefl) [reply lua/telescope/_extensions/zoxide/config.lua:18]: Your plugin your rules, very happy to just override it in my custom config :) My take is that

1) showing sucessfully achieving the user intended behavior isn't something that warants an alert - that's the default expectation. Alerts should be reserved for non-default expectation.
2) Showing the current working directory change is solved through the status line and doesn't appear the responsibility of a switching directory
3) if you use zoxide in the terminal, it doesn't print print the new directory either, so this is inconsistent with zoxide. Equally for cd

Now as a counter argument against myself

vim's `cd`, which this emulates, also appears to print the new directory. I don't like that for the same reasons but it would be inconsistent with it.

Again, I'll take your guidance here - whatever you prefer.

File: lua/telescope/_extensions/zoxide/list.lua (hunk 2 above)
Comment (naefl) [reply lua/telescope/_extensions/zoxide/list.lua:65]: Fair push, can cast

File: lua/telescope/_extensions/zoxide/list.lua (hunk 3 above)
Comment (naefl) [reply lua/telescope/_extensions/zoxide/list.lua:67]: I also was curious why this was added - is there cases where you don't produce a score? otherwise it seems that first pre-space object = score, rest = path seems a reliable heuristic.

I fixed this at like 2am and just wanted to provide #11 a fix so I've only been test driving this for 10mins or so so maybe it breaks!

**Comment by jvgrootveld** [comment]
Tested and merged.
Thanks again @naefl!
